framework:
    rate_limiter:
        api_register:
            policy: fixed_window
            limit: 5
            interval: '1 minute'
        api_contact:
            policy: fixed_window
            limit: 3
            interval: '1 minute'
        api_verify_email:
            policy: sliding_window
            limit: 10
            interval: '1 hour'
        api_reset_password_request:
            policy: sliding_window
            limit: 3
            interval: '1 hour'
        api_reset_password_confirm:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
        api_order_create:
            policy: sliding_window
            limit: 10
            interval: '1 hour'
        api_post_vote:
            policy: sliding_window
            limit: 30
            interval: '1 hour'
